### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ltinker** [grahamgilbert/printer-pkginfo#3]
Hi Graham,

So i had a look through the implementation and had a few suggestions (I am happy to put through merge requests for the actual changes if you think its acceptable)

1. First Suggestion
the following is a part of your code,
`    cmd = [makepkginfo, installcheck_option, postinstall_option, uninstall_option, name_opt, version_opt, '--unattended_install', '--uninstall_method=script', '--nopkg']
`
The first suggestion id like to make is that --uninstall_method=script should probably be --uninstall_method=uninstall_script to bring it inline with https://github.com/munki/munki/wiki/Supported-Pkginfo-Keys.

2. Next suggestion is there is no specification of environments to add so makepkginfo will just default it to 'testing' the requirement here may be different depending on other environments so id like to add that to the printer recipe.

3. Final suggestion is surrounding makepkginfo,
When a nopkg is specified to makepkginfo it does not add any details for the uninstallable key,
due to this tool providing the uninstall script... it should specify the key with the bool value "True"
alternatively this of course could be added to the makepkginfo as a parameter and honestly i feel its probably a more reusable place for it, however my version of this tool i have just added it in my self.

Let me know if you think any of these suggestions are worth while or if you have any feedback regarding any of them.

Regards,
Luke

**Comment by grahamgilbert** [comment]
All sounds fine, would gladly merge in a PR that implements them.

**Comment by grahamgilbert** [comment]
This has been implemented in PR #5
