### ISSUE TITLE
Encoding problem + options 

### ISSUE THREAD

**Issue by yvangodard** [grahamgilbert/printer-pkginfo#4]
Hello,

I use this tool to deploy printers with Munki and it saves me a lot of time. Thank you !
I have some remarks and suggestions ... and as I do not code in Python, I was not able to directly offer you pull request. So I ask you a few questions:

1. Your script does not allow to include specific printer options (like duplex, or other options - cf. https://github.com/munki/munki/wiki/Managing-Printers-With-Munki#how-do-i-find-out-what-options-are-available-to-configure-the-printer-with-duplex-etc - etc.). Does this would be complicated for you to modify with a number of unlimited options? 
At this time, I manually edit the plist before importing in Munki to add these options.

2. Furthermore, I suspect there is a character encoding problem : in the generated file, the "<" character is encoded as "& lt;" for example.

Thank you again for providing this tool.

**Comment by grahamgilbert** [comment]
You can add as many options as you like - see the included example plist. The characters are encoded to be xml safe - this is required by Munki.
